FROM debian:9

ENV NAME askapsoft

# This line instructs debconf to store in its database an answer for the program
# debconf. If (the running program) debconf later asks (the database of answers)
# debconf what is my frontend the answer will be frontend is Noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Install system packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    ant \
    ant-optional \
    astyle \
    autoconf \
    bison \
    build-essential \
    bzip2 \
    clang-format \
    curl \
    exuberant-ctags \
    flex \
    g++ \
    gcc \
    gcc-6-plugin-dev \
    gfortran \
    libatlas-base-dev \
    libatlas-dev \
    libblas-dev \
    libfreetype6 \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    liblapack-dev \
    libmpich2-dev \
    libpng-dev \
    libzmq3-dev \
    linux-headers-amd64 \
    openjdk-8-doc \
    openjdk-8-jdk \
    mpich2 \
    pkg-config \
    python-dev \
    python-gpgme \
    scons \
    subversion \
    sudo \
    unzip \
&& rm -rf /var/lib/apt/lists/*

# Create the askap user, with passwordless sudo permissions
RUN useradd -G users --create-home --password abc --shell /bin/bash askap
RUN echo "askap ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/askap && \
    chmod 0440 /etc/sudoers.d/askap

# Set up the home directory, file ownership, and mount point
ADD askap-home/.bash* /home/askap/
RUN chown -R askap:users /home/askap
WORKDIR /home/askap

# Run as askap user from here on
USER askap

# Set the DISPLAY variable so I can run GUI apps inside the container.
# See: https://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container/25280523#25280523
ENV DISPLAY :0
