FROM askap-debian9-base

# Set up the home directory, file ownership, and mount point
USER root
ADD . /home/askap
RUN chown -R askap:users /home/askap

# Run as askap user from here on
USER askap

# Set the DISPLAY variable so I can run GUI apps inside the container.
# See: https://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container/25280523#25280523
ENV DISPLAY :0

# Update Vim plugins
ENV TERM xterm
RUN echo | echo | vim +qall
RUN echo | echo | vim +PluginInstall! +qall
