FROM debian:8

ENV NAME askapsoft

# This line instructs debconf to store in its database an answer for the program
# debconf. If (the running program) debconf later asks (the database of answers)
# debconf what is my frontend the answer will be frontend is Noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Install system packages
RUN apt-get update && apt-get install -y \
    ant \
    ant-optional \
    astyle \
    autoconf \
    bison \
    build-essential \
    bzip2 \
    clang-format-3.5 \
    curl \
    exuberant-ctags \
    flex \
    fonts-inconsolata \
    fonts-liberation \
    g++ \
    gcc \
    gcc-4.9-plugin-dev \
    gfortran \
    git \
    libatlas-base-dev \
    libatlas-dev \
    libblas-dev \
    libfreetype6 \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    liblapack-dev \
    libopenmpi-dev \
    libpng12-dev \
    libzmq3 \
    libzmq3-dev \
    linux-headers-amd64 \
    meld \
    openjdk-7-doc \
    openjdk-7-jdk \
    openmpi-bin \
    pkg-config \
    python-dev \
    python-gpgme \
    python3-dev \
    python3-pip \
    python3-virtualenv \
    scons \
    subversion \
    sudo \
    terminator \
    tree \
    ttf-dejavu \
    unzip \
    vim-gtk \
    virtualenvwrapper
#&& rm -rf /var/lib/apt/lists/*

# Create the askap user, with passwordless sudo permissions
RUN useradd -G users --create-home --password abc --shell /bin/bash askap
RUN echo "askap ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/askap && \
    chmod 0440 /etc/sudoers.d/askap

# Set up the home directory, file ownership, and mount point
ADD .bash* /home/askap/
VOLUME /home/askap/code
WORKDIR /home/askap
RUN chown -R askap:users /home/askap

# Run as askap user from here on
USER askap
