FROM debian:8

ENV NAME askapsoft

# This line instructs debconf to store in its database an answer for the program
# debconf. If (the running program) debconf later asks (the database of answers)
# debconf what is my frontend the answer will be frontend is Noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

# Install system packages
RUN apt-get update && apt-get install -y \
    ant \
    ant-optional \
    astyle \
    autoconf \
    bison \
    build-essential \
    bzip2 \
    clang-format-3.5 \
    curl \
    exuberant-ctags \
    flex \
    g++ \
    gcc \
    gcc-4.9-plugin-dev \
    gfortran \
    git \
    libatlas-base-dev \
    libatlas-dev \
    libblas-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    liblapack-dev \
    libopenmpi-dev \
    libpng12-dev \
    libzmq3 \
    libzmq3-dev \
    linux-headers-amd64 \
    meld \
    openjdk-7-doc \
    openjdk-7-jdk \
    openmpi-bin \
    python-dev \
    python-gpgme \
    python3-dev \
    python3-pip \
    python3-virtualenv \
    scons \
    subversion \
    sudo \
    tree \
    unzip \
    vim-gtk \
    virtualenvwrapper
#&& rm -rf /var/lib/apt/lists/*

# Create the askap user, with sudo permissions
RUN adduser askapuser
RUN echo "user ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/askapuser && \
    chmod 0440 /etc/sudoers.d/askapuser
WORKDIR /home/askapuser

# Set up the home directory and mount point
ADD . /home/askapuser
#RUN mkdir /home/askapuser/askapsoft
RUN chown -R askapuser:askapuser /home/askapuser
VOLUME /home/askapuser/code

USER askapuser

# Set the DISPLAY variable so I can run GUI apps inside the container.
# See: https://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container/25280523#25280523
ENV DISPLAY :0

# Update Vim plugins
ENV TERM xterm
RUN echo | echo | vim +qall
RUN echo | echo | vim +PluginInstall! +qall
