FROM askap-debian8:latest

# Install additional system packages
RUN sudo apt-get update && sudo apt-get install -y --no-install-recommends \
    exuberant-ctags \
    gcc-4.9-plugin-dev \
    git \
    meld \
    python3 \
    python3-dev \
    python3-pip \
    tree \
    ttf-dejavu \
    vim-gtk \
    virtualenv \
    virtualenvwrapper
#&& rm -rf /var/lib/apt/lists/*
