#!/bin/bash

IMAGE=askap/$1
VERSION=${2:-latest}
VOLUME=askap-$1

if [[ $1 = 'gui-dev' ]]; then
    # Set up the X11 stuff ...
    XSOCK=/tmp/.X11-unix
    XAUTH=/tmp/.docker.xauth
    xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
    XAUTH_ARGS="--volume $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH"
fi

# run the specified image
docker run \
 --hostname $IMAGE:$VERSION \
 --tty \
 --interactive \
 --rm \
 --mount source=$VOLUME,target=/home/askap/ \
 $XAUTH_ARGS \
 $IMAGE:$VERSION

#--mount type=bind,source="$HOME/code/askap-builds/",target=/askap-builds/ \
