#!/bin/bash

# Set up the X11 stuff ...
echo Enabling X11 forwarding
XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth
xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
XAUTH_ARGS="--volume $XSOCK:$XSOCK -v $XAUTH:$XAUTH -e XAUTHORITY=$XAUTH"

SOURCE_CODE_MOUNT="--mount type=bind,source=/home/daniel/code/python-profiling/,target=/home/user/code/"

# run the specified image
docker run \
 --hostname xdot \
 --tty \
 --interactive \
 --rm \
 --mount source=xdot-volume,target=/home/user/ \
 $SOURCE_CODE_MOUNT \
 $XAUTH_ARGS \
 xdot:latest
